// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using techiz.Persistence;

#nullable disable

namespace techiz.Persistence.Migrations
{
    [DbContext(typeof(appDbContext))]
    [Migration("20230128211305_mig20")]
    partial class mig20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "edb2d0bb-ba33-409e-b854-f194e4066c09",
                            ConcurrencyStamp = "068d55e5-bb4b-4548-a245-1cb07f78625f",
                            Name = "sistemadmin",
                            NormalizedName = "SİSTEMADMİN"
                        },
                        new
                        {
                            Id = "bc59f93b-675a-470f-b4b3-cf19f4dfce15",
                            ConcurrencyStamp = "70e01d0f-2b83-4d10-9ebe-a3651bf93838",
                            Name = "admin",
                            NormalizedName = "ADMİN"
                        },
                        new
                        {
                            Id = "5d3ae569-31c3-47cd-9f75-7425a83b853f",
                            ConcurrencyStamp = "7b7a77ec-578e-4a8f-a003-f57991e097ed",
                            Name = "depo",
                            NormalizedName = "DEPO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RoleClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.HasKey("UserId", "ProviderKey");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Value");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("techiz.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("techiz.Domain.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Eposta")
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.Property<string>("TelefonGSM")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa32f950-e147-4c40-ab4b-a1daff2c800b"),
                            AccessFailedCount = 0,
                            Ad = "Hakan",
                            ConcurrencyStamp = "53aa8404-b9e4-48ec-839e-5bd84d4d4d69",
                            Email = "hakan@oxit.com",
                            EmailConfirmed = false,
                            Eposta = "hakan@oxit.com",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLjouNqaeiVWbN0TbXUS3+ChW3d7aQIk/BQEkWBxlrdRRngp14b0BIH0Rp65qD6mA==",
                            PhoneNumberConfirmed = false,
                            Soyad = "YILDIRIM",
                            TwoFactorEnabled = false,
                            UserName = "hakanyildirim"
                        },
                        new
                        {
                            Id = new Guid("45416332-af69-4a90-b464-41435ad180bc"),
                            AccessFailedCount = 0,
                            Ad = "Seref",
                            ConcurrencyStamp = "ef0dcfcc-ee4f-4716-9d0a-d1b62e58fa65",
                            Email = "seref@oxit.com",
                            EmailConfirmed = false,
                            Eposta = "seref@oxit.com",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BASICUSER@GMAIL.COM",
                            NormalizedUserName = "BASICUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLjouNqaeiVWbN0TbXUS3+ChW3d7aQIk/BQEkWBxlrdRRngp14b0BIH0Rp65qD6mA==",
                            PhoneNumberConfirmed = false,
                            Soyad = "Bagin",
                            TwoFactorEnabled = false,
                            UserName = "Seref"
                        },
                        new
                        {
                            Id = new Guid("d72cb300-45b1-4487-99c3-12ca06bd6878"),
                            AccessFailedCount = 0,
                            Ad = "Hakki",
                            ConcurrencyStamp = "bb4bd985-17fd-497b-a0fc-f6b6b48d284f",
                            Email = "hakki@oxit.com",
                            EmailConfirmed = false,
                            Eposta = "hakki@oxit.com",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BASICUSER@GMAIL.COM",
                            NormalizedUserName = "BASICUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLjouNqaeiVWbN0TbXUS3+ChW3d7aQIk/BQEkWBxlrdRRngp14b0BIH0Rp65qD6mA==",
                            PhoneNumberConfirmed = false,
                            Soyad = "Şimşek",
                            TwoFactorEnabled = false,
                            UserName = "Hakki"
                        },
                        new
                        {
                            Id = new Guid("137f5f71-9923-472d-b07c-bfe1c11d2800"),
                            AccessFailedCount = 0,
                            Ad = "Tolga",
                            ConcurrencyStamp = "ab5039be-dd80-41e9-b868-44fa46c0cdb3",
                            Email = "tolga@oxit.com",
                            EmailConfirmed = true,
                            Eposta = "tolga@oxit.com",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BASICUSER@GMAIL.COM",
                            NormalizedUserName = "BASICUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLjouNqaeiVWbN0TbXUS3+ChW3d7aQIk/BQEkWBxlrdRRngp14b0BIH0Rp65qD6mA==",
                            PhoneNumberConfirmed = false,
                            Soyad = "Bagin",
                            TwoFactorEnabled = false,
                            UserName = "Tolga"
                        });
                });

            modelBuilder.Entity("techiz.Domain.Entities.BomKitInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("IsKitPreperated")
                        .HasColumnType("integer");

                    b.Property<int>("IsKitProvided")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProductionProcess")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSetupVerification")
                        .HasColumnType("boolean");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("PartyNumber")
                        .HasColumnType("text");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<double?>("RollerQuantity")
                        .HasColumnType("double precision");

                    b.Property<int?>("SetNo")
                        .HasColumnType("integer");

                    b.Property<string>("SoureProductPlace")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<int?>("WareHouseId")
                        .HasColumnType("integer");

                    b.Property<string>("WareHouseName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("WareHouseId");

                    b.ToTable("BomKitInfo");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BarcodeReaderId")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LedNumber")
                        .HasColumnType("integer");

                    b.Property<int>("LineId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("integer");

                    b.Property<string>("RouteLink")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 470, DateTimeKind.Unspecified).AddTicks(9150), new TimeSpan(0, 3, 0, 0, 0)),
                            Icon = "pi pi-fw pi-globe",
                            IsDeleted = false,
                            Label = "Panel",
                            RouteLink = "/"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 470, DateTimeKind.Unspecified).AddTicks(9190), new TimeSpan(0, 3, 0, 0, 0)),
                            Icon = "fa fa-gavel",
                            IsDeleted = false,
                            Label = "Kullanıcı",
                            RouteLink = "/kullanıcı"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 470, DateTimeKind.Unspecified).AddTicks(9200), new TimeSpan(0, 3, 0, 0, 0)),
                            Icon = "fa fa-balance-scale",
                            IsDeleted = false,
                            Label = "Kullanıcı Grup",
                            RouteLink = "/kullanicigrup"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 470, DateTimeKind.Unspecified).AddTicks(9200), new TimeSpan(0, 3, 0, 0, 0)),
                            Icon = "pi pi-fw pi-id-card",
                            IsDeleted = false,
                            Label = "Tanımlar",
                            RouteLink = "/tanimlar"
                        });
                });

            modelBuilder.Entity("techiz.Domain.Entities.MenuPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("PermissionId");

                    b.ToTable("MenuPermission");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 470, DateTimeKind.Unspecified).AddTicks(9940), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.Genel.All"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(110), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.Uretim.All"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(310), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.KitHazirlama.All"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(440), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.KitDogrulama.All"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(600), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.SetupVerification.All"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(720), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.Ayarlar.All"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(890), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.Credential.All"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(1090), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Role.Goruntule"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(1390), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Role.Kaydet"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(1520), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Role.Sil"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(2110), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kullanıcı.Goruntule"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(2410), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kullanıcı.Kaydet"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(2770), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kullanıcı.Sil"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(3120), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.KullaniciGrup.All"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 471, DateTimeKind.Unspecified).AddTicks(3250), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.Log.All"
                        });
                });

            modelBuilder.Entity("techiz.Domain.Entities.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNo")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UretimAdi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Production");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionProcess")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductionLog");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionOperations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeedlerData")
                        .HasColumnType("jsonb");

                    b.Property<int>("GecenSure")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("OperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperationProcess")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<int?>("SetupVerificationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("SetupVerificationId");

                    b.ToTable("ProductionOperations");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionOperationsTimeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentTime")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LastTime")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionOperationsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("ProductionOperationsId");

                    b.ToTable("ProductionOperationsTimeLog");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionTimeProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ElapsedTime")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionProcess")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionTimeStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("RestCauseId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("RestCauseId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductionTimeProcess");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<bool>("OpenState")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionProcess")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductionUser");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionUserRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionProcess")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductionUserRelation");
                });

            modelBuilder.Entity("techiz.Domain.Entities.RestCause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RestCause");
                });

            modelBuilder.Entity("techiz.Domain.Entities.RouteInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("Operation")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<string>("RouteStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorkCentreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkCentreId");

                    b.ToTable("RouteInfo");
                });

            modelBuilder.Entity("techiz.Domain.Entities.SetupVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductionId");

                    b.ToTable("SetupVerification");
                });

            modelBuilder.Entity("techiz.Domain.Entities.SetupVerificationDChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NewPanelId")
                        .HasColumnType("integer");

                    b.Property<int>("OldPanelId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("SetupVerificationDetailsNewId")
                        .HasColumnType("integer");

                    b.Property<int>("SetupVerificationDetailsOldId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewPanelId");

                    b.HasIndex("OldPanelId");

                    b.HasIndex("ProductionId");

                    b.HasIndex("SetupVerificationDetailsNewId");

                    b.HasIndex("SetupVerificationDetailsOldId");

                    b.ToTable("SetupVerificationDChange");
                });

            modelBuilder.Entity("techiz.Domain.Entities.SetupVerificationDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("BomKitInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("ChangingBomKitInfoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<double?>("FinishingQuantity")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MachineId")
                        .HasColumnType("integer");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("PartyNumber")
                        .HasColumnType("text");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<double?>("RollerQuantity")
                        .HasColumnType("double precision");

                    b.Property<int>("SetNo")
                        .HasColumnType("integer");

                    b.Property<int>("SetupVerificationId")
                        .HasColumnType("integer");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<bool?>("State")
                        .HasColumnType("boolean");

                    b.Property<double?>("UsingQuantity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BomKitInfoId");

                    b.HasIndex("MachineId");

                    b.HasIndex("SetupVerificationId");

                    b.ToTable("SetupVerificationDetails");
                });

            modelBuilder.Entity("techiz.Domain.Entities.SetupVerificationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Decrease")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerificated")
                        .HasColumnType("boolean");

                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<double?>("RollerQuantity")
                        .HasColumnType("double precision");

                    b.Property<int>("SetNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductionId");

                    b.ToTable("SetupVerificationInfo");
                });

            modelBuilder.Entity("techiz.Domain.Entities.WareHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WareHouse");
                });

            modelBuilder.Entity("techiz.Domain.Entities.WorkCentre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkCentre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 473, DateTimeKind.Unspecified).AddTicks(810), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "DEPO"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 473, DateTimeKind.Unspecified).AddTicks(850), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "SMT DZG"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 473, DateTimeKind.Unspecified).AddTicks(860), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "THT DZG"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 473, DateTimeKind.Unspecified).AddTicks(860), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "KLT"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 1, 29, 0, 13, 4, 473, DateTimeKind.Unspecified).AddTicks(860), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "KMYSL"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("techiz.Domain.Auth.User", null)
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("techiz.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("techiz.Domain.Auth.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("techiz.Domain.Entities.BomKitInfo", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany("BomKitInfo")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.WareHouse", "WareHouse")
                        .WithMany("BomKitInfo")
                        .HasForeignKey("WareHouseId");

                    b.Navigation("Production");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Machine", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Line", "Line")
                        .WithMany("Machine")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Menu", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Menu", "ParentMenu")
                        .WithMany("items")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("techiz.Domain.Entities.MenuPermission", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Menu", "Menu")
                        .WithMany("MenuPermission")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Menu");

                    b.HasOne("techiz.Domain.Entities.Permission", "Permission")
                        .WithMany("MenuPermission")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Permission_MenuPermission");

                    b.Navigation("Menu");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionLog", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany("ProductionLog")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Auth.User", "User")
                        .WithMany("ProductionLog")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");

                    b.Navigation("User");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionOperations", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany("ProductionOperations")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.SetupVerification", null)
                        .WithMany("ProductionOperations")
                        .HasForeignKey("SetupVerificationId");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionOperationsTimeLog", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.ProductionOperations", "ProductionOperations")
                        .WithMany()
                        .HasForeignKey("ProductionOperationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");

                    b.Navigation("ProductionOperations");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionTimeProcess", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany("ProductionTimeProcess")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.RestCause", "RestCause")
                        .WithMany("ProductionTimeProcess")
                        .HasForeignKey("RestCauseId");

                    b.HasOne("techiz.Domain.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");

                    b.Navigation("RestCause");

                    b.Navigation("User");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionUser", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany("ProductionUser")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Auth.User", "User")
                        .WithMany("ProductionUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");

                    b.Navigation("User");
                });

            modelBuilder.Entity("techiz.Domain.Entities.ProductionUserRelation", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Auth.User", "User")
                        .WithMany("ProductionUserRelation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");

                    b.Navigation("User");
                });

            modelBuilder.Entity("techiz.Domain.Entities.RouteInfo", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany("RouteInfo")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("techiz.Domain.Entities.WorkCentre", "WorkCentre")
                        .WithMany("RouteInfo")
                        .HasForeignKey("WorkCentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");

                    b.Navigation("User");

                    b.Navigation("WorkCentre");
                });

            modelBuilder.Entity("techiz.Domain.Entities.SetupVerification", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Machine", "Machine")
                        .WithMany("SetupVerification")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany("SetupVerification")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("techiz.Domain.Entities.SetupVerificationDChange", b =>
                {
                    b.HasOne("techiz.Domain.Entities.ProductionOperations", "NewPanel")
                        .WithMany()
                        .HasForeignKey("NewPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.ProductionOperations", "OldPanel")
                        .WithMany()
                        .HasForeignKey("OldPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany("SetupVerificationDChange")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.SetupVerificationDetails", "SetupVerificationDetailsNew")
                        .WithMany()
                        .HasForeignKey("SetupVerificationDetailsNewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.SetupVerificationDetails", "SetupVerificationDetailsOld")
                        .WithMany()
                        .HasForeignKey("SetupVerificationDetailsOldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SetupVerificationDChange_SetupVerificationDetails_SetupVer~1");

                    b.Navigation("NewPanel");

                    b.Navigation("OldPanel");

                    b.Navigation("Production");

                    b.Navigation("SetupVerificationDetailsNew");

                    b.Navigation("SetupVerificationDetailsOld");
                });

            modelBuilder.Entity("techiz.Domain.Entities.SetupVerificationDetails", b =>
                {
                    b.HasOne("techiz.Domain.Entities.BomKitInfo", "BomKitInfo")
                        .WithMany("SetupVerificationDetails")
                        .HasForeignKey("BomKitInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.Machine", "Machine")
                        .WithMany("SetupVerificationDetails")
                        .HasForeignKey("MachineId");

                    b.HasOne("techiz.Domain.Entities.SetupVerification", "SetupVerification")
                        .WithMany("SetupVerificationDetails")
                        .HasForeignKey("SetupVerificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomKitInfo");

                    b.Navigation("Machine");

                    b.Navigation("SetupVerification");
                });

            modelBuilder.Entity("techiz.Domain.Entities.SetupVerificationInfo", b =>
                {
                    b.HasOne("techiz.Domain.Entities.Machine", "Machine")
                        .WithMany("SetupVerificationInfo")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("techiz.Domain.Entities.Production", "Production")
                        .WithMany("SetupVerificationInfo")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("techiz.Domain.Auth.User", b =>
                {
                    b.Navigation("ProductionLog");

                    b.Navigation("ProductionUser");

                    b.Navigation("ProductionUserRelation");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("techiz.Domain.Entities.BomKitInfo", b =>
                {
                    b.Navigation("SetupVerificationDetails");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Line", b =>
                {
                    b.Navigation("Machine");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Machine", b =>
                {
                    b.Navigation("SetupVerification");

                    b.Navigation("SetupVerificationDetails");

                    b.Navigation("SetupVerificationInfo");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Menu", b =>
                {
                    b.Navigation("MenuPermission");

                    b.Navigation("items");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Permission", b =>
                {
                    b.Navigation("MenuPermission");
                });

            modelBuilder.Entity("techiz.Domain.Entities.Production", b =>
                {
                    b.Navigation("BomKitInfo");

                    b.Navigation("ProductionLog");

                    b.Navigation("ProductionOperations");

                    b.Navigation("ProductionTimeProcess");

                    b.Navigation("ProductionUser");

                    b.Navigation("RouteInfo");

                    b.Navigation("SetupVerification");

                    b.Navigation("SetupVerificationDChange");

                    b.Navigation("SetupVerificationInfo");
                });

            modelBuilder.Entity("techiz.Domain.Entities.RestCause", b =>
                {
                    b.Navigation("ProductionTimeProcess");
                });

            modelBuilder.Entity("techiz.Domain.Entities.SetupVerification", b =>
                {
                    b.Navigation("ProductionOperations");

                    b.Navigation("SetupVerificationDetails");
                });

            modelBuilder.Entity("techiz.Domain.Entities.WareHouse", b =>
                {
                    b.Navigation("BomKitInfo");
                });

            modelBuilder.Entity("techiz.Domain.Entities.WorkCentre", b =>
                {
                    b.Navigation("RouteInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
