// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eShop.Persistence;

#nullable disable

namespace eShop.Persistence.Migrations
{
    [DbContext(typeof(appDbContext))]
    [Migration("20241101213519_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "ccd8dac9-1d84-4ba2-ad73-0621b8ddd4ab",
                            Name = "sistemadmin",
                            NormalizedName = "SISTEMADMIN"
                        },
                        new
                        {
                            Id = "aea0cebf-e106-4de9-8b24-ff043e4b5b17",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "02a199d9-be66-4988-8eb3-37b9fe96a95d",
                            Name = "depo",
                            NormalizedName = "DEPO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RoleClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.HasKey("UserId", "ProviderKey");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Value");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("eShop.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("eShop.Domain.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Eposta")
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.Property<string>("TelefonGSM")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("65217fea-4a15-4154-928b-4cbfef53f80d"),
                            AccessFailedCount = 0,
                            Ad = "Hakan",
                            ConcurrencyStamp = "f07e197a-c71f-4e42-a5a1-29ec44dec85f",
                            Email = "hakan@.com",
                            EmailConfirmed = false,
                            Eposta = "hakan@.com",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLjouNqaeiVWbN0TbXUS3+ChW3d7aQIk/BQEkWBxlrdRRngp14b0BIH0Rp65qD6mA==",
                            PhoneNumberConfirmed = false,
                            Soyad = "YILDIRIM",
                            TwoFactorEnabled = false,
                            UserName = "hakanyildirim"
                        },
                        new
                        {
                            Id = new Guid("48af3a8e-cb3d-49a0-8bba-97580c8df050"),
                            AccessFailedCount = 0,
                            Ad = "Tolga",
                            ConcurrencyStamp = "152ab07c-29b2-496f-b6ec-2300c35c725a",
                            Email = "tolga@.com",
                            EmailConfirmed = true,
                            Eposta = "tolga@.com",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BASICUSER@GMAIL.COM",
                            NormalizedUserName = "BASICUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLjouNqaeiVWbN0TbXUS3+ChW3d7aQIk/BQEkWBxlrdRRngp14b0BIH0Rp65qD6mA==",
                            PhoneNumberConfirmed = false,
                            Soyad = "Bagin",
                            TwoFactorEnabled = false,
                            UserName = "Tolga"
                        },
                        new
                        {
                            Id = new Guid("8e2ed5bf-afc4-4b75-8116-b2419b373a5e"),
                            AccessFailedCount = 0,
                            Ad = "Salih",
                            ConcurrencyStamp = "56695399-1ef2-4f0c-bc25-d80965f5f741",
                            Email = "salih@.com",
                            EmailConfirmed = true,
                            Eposta = "salih@.com",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BASICUSER@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLjouNqaeiVWbN0TbXUS3+ChW3d7aQIk/BQEkWBxlrdRRngp14b0BIH0Rp65qD6mA==",
                            PhoneNumberConfirmed = false,
                            Soyad = "Dürüs",
                            TwoFactorEnabled = false,
                            UserName = "Salih"
                        },
                        new
                        {
                            Id = new Guid("cfd11b99-dde3-474a-aad0-cd2015f9d747"),
                            AccessFailedCount = 0,
                            Ad = "Cagan",
                            ConcurrencyStamp = "cf4981d2-2f0b-4189-b0bf-c8133155e012",
                            Email = "cagan@.com",
                            EmailConfirmed = true,
                            Eposta = "cagan@.com",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BASICUSER@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLjouNqaeiVWbN0TbXUS3+ChW3d7aQIk/BQEkWBxlrdRRngp14b0BIH0Rp65qD6mA==",
                            PhoneNumberConfirmed = false,
                            Soyad = "Turhan",
                            TwoFactorEnabled = false,
                            UserName = "cagan"
                        },
                        new
                        {
                            Id = new Guid("5a77d16f-7897-47c3-bf75-608b28649d2a"),
                            AccessFailedCount = 0,
                            Ad = "eShop",
                            ConcurrencyStamp = "2f2ec740-5fdd-4fe8-981f-f1e3f84e8324",
                            Email = "eShop@sentytech.com",
                            EmailConfirmed = true,
                            Eposta = "eShop@sentytech.com",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BASICUSER@GMAIL.COM",
                            NormalizedUserName = "BASICUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLjouNqaeiVWbN0TbXUS3+ChW3d7aQIk/BQEkWBxlrdRRngp14b0BIH0Rp65qD6mA==",
                            PhoneNumberConfirmed = false,
                            Soyad = "eShop",
                            TwoFactorEnabled = false,
                            UserName = "eShop"
                        });
                });

            modelBuilder.Entity("eShop.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<double?>("DecreaseQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("NextWPRId")
                        .HasColumnType("integer");

                    b.Property<string>("PartyNumber")
                        .HasColumnType("text");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<double?>("RemainQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("eShop.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("integer");

                    b.Property<string>("RouteLink")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(3164), new TimeSpan(0, 3, 0, 0, 0)),
                            Icon = "pi pi-fw pi-globe",
                            IsDeleted = false,
                            Label = "Panel",
                            RouteLink = "/"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(3208), new TimeSpan(0, 3, 0, 0, 0)),
                            Icon = "fa fa-gavel",
                            IsDeleted = false,
                            Label = "Kullanıcı",
                            RouteLink = "/kullanıcı"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(3211), new TimeSpan(0, 3, 0, 0, 0)),
                            Icon = "fa fa-balance-scale",
                            IsDeleted = false,
                            Label = "Kullanıcı Grup",
                            RouteLink = "/kullanicigrup"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(3213), new TimeSpan(0, 3, 0, 0, 0)),
                            Icon = "pi pi-fw pi-id-card",
                            IsDeleted = false,
                            Label = "Tanımlar",
                            RouteLink = "/tanimlar"
                        });
                });

            modelBuilder.Entity("eShop.Domain.Entities.MenuPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("PermissionId");

                    b.ToTable("MenuPermission");
                });

            modelBuilder.Entity("eShop.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(3479), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Permissions.Genel.All"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(3793), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Üretim Bandı"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(4047), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Etiketleme"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(4300), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Display Montajı"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(4537), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Programlama"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(4821), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Panelden Ayırma"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(5091), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Test"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(5343), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kalite Süreçler"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(5632), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kalite Onaylar"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(5888), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kalite Operasyonlar"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(6185), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Depo Tanımları"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(6424), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Hat Tanımları"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(6723), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Makine Tanımları"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(6993), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Vardiya Tanımları"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(7265), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Oee Gösterim"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(7522), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Vardiya - Hat Hedef Miktar Tanımları"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(7773), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Mola Tanımları"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(8027), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Tamamlanan Kalite Operasyonları"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(8277), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Üretim Planlama"
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(8684), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Üretim Planlama Görüntüle"
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(8968), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Üretim Planlama Kaydet"
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(9228), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Üretim Planlama Sil"
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(9547), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kit Hazırlama"
                        },
                        new
                        {
                            Id = 24,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 870, DateTimeKind.Unspecified).AddTicks(9838), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kit Doğrulama"
                        },
                        new
                        {
                            Id = 25,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(227), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Setup Verification"
                        },
                        new
                        {
                            Id = 26,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(516), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Ayarlar"
                        },
                        new
                        {
                            Id = 27,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(906), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Credential"
                        },
                        new
                        {
                            Id = 28,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(1374), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kalite"
                        },
                        new
                        {
                            Id = 29,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(1766), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Dashboard"
                        },
                        new
                        {
                            Id = 30,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(2087), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Rol Görüntüle"
                        },
                        new
                        {
                            Id = 31,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(2507), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Rol Kaydet"
                        },
                        new
                        {
                            Id = 32,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(2886), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Rol Sil"
                        },
                        new
                        {
                            Id = 33,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(3164), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kullanıcı Görüntüle"
                        },
                        new
                        {
                            Id = 34,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(3439), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kullanıcı Kaydet"
                        },
                        new
                        {
                            Id = 35,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(3696), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Kullanıcı Sil"
                        },
                        new
                        {
                            Id = 36,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(3953), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "KullaniciGrup All"
                        },
                        new
                        {
                            Id = 37,
                            Active = true,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 11, 2, 0, 35, 18, 871, DateTimeKind.Unspecified).AddTicks(4200), new TimeSpan(0, 3, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "LogAll"
                        });
                });

            modelBuilder.Entity("eShop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("BuyingPrice")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomsNr")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNr")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Length")
                        .HasColumnType("text");

                    b.Property<string>("NameDe")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("NameTR")
                        .HasColumnType("text");

                    b.Property<string>("OrjinalNr")
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .HasColumnType("text");

                    b.Property<string>("Width")
                        .HasColumnType("text");

                    b.Property<string>("Wieght")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("eShop.Domain.Auth.User", null)
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("eShop.Domain.Auth.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Domain.Entities.Menu", b =>
                {
                    b.HasOne("eShop.Domain.Entities.Menu", "ParentMenu")
                        .WithMany("items")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("eShop.Domain.Entities.MenuPermission", b =>
                {
                    b.HasOne("eShop.Domain.Entities.Menu", "Menu")
                        .WithMany("MenuPermission")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Menu");

                    b.HasOne("eShop.Domain.Entities.Permission", "Permission")
                        .WithMany("MenuPermission")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Permission_MenuPermission");

                    b.Navigation("Menu");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("eShop.Domain.Auth.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("eShop.Domain.Entities.Menu", b =>
                {
                    b.Navigation("MenuPermission");

                    b.Navigation("items");
                });

            modelBuilder.Entity("eShop.Domain.Entities.Permission", b =>
                {
                    b.Navigation("MenuPermission");
                });
#pragma warning restore 612, 618
        }
    }
}
